### PR TITLE
Add changes required by alisw/alidist#387

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@alisw/pwgmm I suppose this is the set of changes you actually need by alisw/alidist#387, right? If that is the case, please merge this PR and I will start the build of a new version.

**Comment by ktf** [comment]
By the way, IMHO, you should avoid having a branch named `next/.*` and simply rely on pull requests from other repositories for that.

**Comment by qgp** [comment]
@ktf: thanks, merged. Maybe I misunderstood the policy, I thought that changes staged for the next release should go to `next/.*` as it is done for `alidist`. Whatever PR is accepted for merge to alice/.\* would be picked up by a re-installation (also for an end-user running aliBuild to install this locally). Thus, we would not have the option to prepare a next release before actually making it active.

Maybe I just miss something in this reasoning?

**Comment by ktf** [comment]
Well, you would have the PR to check the changes, no? Once we merge the PR and we trigger a rebuild, the changes would get deployed.

**Comment by qgp** [comment]
Ok, then sorry for the "mess", I'll avoid it in the future unless it's really something big we don't want to get immediately. Thanks for the clarification.

**Comment by ktf** [comment]
No worries. Indeed I think the best rationale is to keep only minor developments in this repository (and therefore they can happen with PR) and if a really big one is needed it's probably better to try to push the changes upstream.

**Pull request merged**
