### PR TITLE
import POWHEG-BOX-V2 rev 3693

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
As discussed in #2 these are the original sources to be merged into master. From the master there can be new branch opened with the ALICE-specific patches. From the patch branch a new tag with the POWHEG version should be created.

@qgp @maireihpc

**Comment by mfasDa** [comment]
The ALICE patch for the dijet makefile is now separated and can be found here: https://github.com/mfasDa/POWHEG/tree/alice/r3693-1

**Review by maireiphc — APPROVED** [review]

**Comment by mfasDa** [comment]
@qgp Thanks for merging! Can you please create the branch alice/r3693?

**Comment by qgp** [comment]
> @qgp Thanks for merging! Can you please create the branch alice/r3693?

@mfasDa done

**Pull request merged**
