### PR TITLE
Import POWHEG-BOX-V2 rev 3964

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Review by maireiphc — APPROVED** [review]

**Comment by maireiphc** [comment]
Hello @mfasDa (@ktf, @TimoWilken @alisw/pagmc @qgp),

  it seems that PAG-MC (Antonio de silva and myself) are not the owners of alisw/POWHEG.
At least @ktf and @TimoWilken could i) approve and ii) tag a release.
Maybe also @qgp (inheritance from past).

**Comment by ktf** [comment]
@alisw/pagmc is now admin.

**Comment by mfasDa** [comment]
Thanks @maireiphc! However we also need the tag so that I can change it in the build recipe.

**Comment by maireiphc** [comment]
Hello @mfasDa, the tag/release is now done, with the name `r3964-alice1`
https://github.com/alisw/POWHEG/releases/tag/r3964-alice1

I propose that we may wait tomorrow AliGenerators building via Jenkins at 16:00 before changing the GitHub pointer.
For the sake of the test.
i.e. tomorrow 27 Apr 2022 : pick `r3964-alice1` from your https://github.com/mfasDa/POWHEG
and later on, update the alidist recipe to pick the equivalent from https://github.com/alisw/POWHEG

Giulio anyhow already merged this commit to alidist master
Is it ok for you ?

**Pull request merged**
